[[admins]]
chat_id = 1
name = "]]]]]]]]"
username = "1"
is_admin = true

[[admins]]
chat_id = 2
name = "[[[[[[[["
username = "2"
is_admin = true

[[admins]]
chat_id = 3
name = "{{{{{{"
username = "3"
is_admin = true

